version: '3.3'
services:


  redis:
    image: redis:latest

  postgres:
    image: postgres:latest
    environment:
     - POSTGRES_DB=django
     - POSTGRES_USER=ludkadj
     - POSTGRES_PASSWORD=ludkadj

  django: &base_container
    image: ludka/django-blog:latest
    ports:
      - "8000:8000"
    volumes:
      - ./:/app/
    depends_on:
      - postgres
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
    command: |
      python manage.py runserver 0.0.0.0:8000

  worker:
    <<: *base_container
    ports: []
    command: |
      python manage.py rqworker default

  bot:
    <<: *base_container
    ports: [ ]
    environment:
      - DATABASE_HOST=postgres
      - REDIS_HOST=redis
      - BOT_TOKEN=5674717393:AAEwt1bWE6ceITV91XjHbvdjFvCU773u9cQ
      - CHAT_ID=1327834481
    command: |
      python manage.py run_bot